(custom-set-variables
 '(message-sendmail-f-is-evil t)
 '(recent-files-commands-submenu t)
 '(sgml-catalog-files '("CATALOG" "/export/home/houghton/work/Support/share/dtd/DocTools/CATALOG" "/Tools/lib/xemacs/xemacs-packages/etc/psgml/CATALOG")
)
 '(cperl-mode-hook '(my-cperl-hook)
)
 '(c-default-style '((java-mode . "java")
  (other . "gnu"))
)
 '(package-get-download-sites '(("Pre-Releases" "ftp.xemacs.org" "pub/xemacs/beta/experimental/packages")
  ("Cscape" "cscape.wcomnet.com" "pub/xemacs/packages")
  ("xemacs.org" "ftp.xemacs.org" "pub/xemacs/packages")
  ("crc.ca (Canada)" "ftp.crc.ca" "pub/packages/editors/xemacs/packages")
  ("ualberta.ca (Canada)" "sunsite.ualberta.ca" "pub/Mirror/xemacs/packages")
  ("uiuc.edu (United States)" "uiarchive.uiuc.edu" "pub/packages/xemacs/packages")
  ("unc.edu (United States)" "metalab.unc.edu" "pub/packages/editors/xemacs/packages")
  ("utk.edu (United States)" "ftp.sunsite.utk.edu" "pub/xemacs/packages")
  ("unicamp.br (Brazil)" "ftp.unicamp.br" "pub/xemacs/packages")
  ("tuwien.ac.at (Austria)" "gd.tuwien.ac.at" "editors/xemacs/packages")
  ("auc.dk (Denmark)" "sunsite.auc.dk" "pub/emacs/xemacs/packages")
  ("doc.ic.ac.uk (England)" "sunsite.doc.ic.ac.uk" "packages/xemacs/packages")
  ("funet.fi (Finland)" "ftp.funet.fi" "pub/mirrors/ftp.xemacs.org/pub/tux/xemacs/packages")
  ("cenatls.cena.dgac.fr (France)" "ftp.cenatls.cena.dgac.fr" "Emacs/xemacs/packages")
  ("pasteur.fr (France)" "ftp.pasteur.fr" "pub/computing/xemacs/packages")
  ("tu-darmstadt.de (Germany)" "ftp.tu-darmstadt.de" "pub/editors/xemacs/packages")
  ("kfki.hu (Hungary)" "ftp.kfki.hu" "pub/packages/xemacs/packages")
  ("eunet.ie (Ireland)" "ftp.eunet.ie" "mirrors/ftp.xemacs.org/pub/xemacs/packages")
  ("uniroma2.it (Italy)" "ftp.uniroma2.it" "unix/misc/dist/XEMACS/packages")
  ("uio.no (Norway)" "sunsite.uio.no" "pub/xemacs/packages")
  ("icm.edu.pl (Poland)" "ftp.icm.edu.pl" "pub/unix/editors/xemacs/packages")
  ("srcc.msu.su (Russia)" "ftp.srcc.msu.su" "mirror/ftp.xemacs.org/packages")
  ("sunet.se (Sweden)" "ftp.sunet.se" "pub/gnu/xemacs/packages")
  ("cnlab-switch.ch (Switzerland)" "sunsite.cnlab-switch.ch" "mirror/xemacs/packages")
  ("aist.go.jp (Japan)" "ring.aist.go.jp" "pub/text/xemacs/packages")
  ("asahi-net.or.jp (Japan)" "ring.asahi-net.or.jp" "pub/text/xemacs/packages")
  ("dti.ad.jp (Japan)" "ftp.dti.ad.jp" "pub/unix/editor/xemacs/packages")
  ("jaist.ac.jp (Japan)" "ftp.jaist.ac.jp" "pub/GNU/xemacs/packages")
  ("nucba.ac.jp (Japan)" "mirror.nucba.ac.jp" "mirror/xemacs/packages")
  ("sut.ac.jp (Japan)" "sunsite.sut.ac.jp" "pub/archives/packages/xemacs/packages")
  ("tsukuba.ac.jp (Japan)" "ftp.netlab.is.tsukuba.ac.jp" "pub/GNU/xemacs/packages")
  ("kreonet.re.kr (Korea)" "ftp.kreonet.re.kr" "pub/tools/emacs/xemacs/packages")
  ("nctu.edu.tw (Taiwan)" "coda.nctu.edu.tw" "Editors/xemacs/packages")
  ("sun.ac.za (South Africa)" "ftp.sun.ac.za" "xemacs/packages")
  ("isu.net.sa (Saudi Arabia)" "ftp.isu.net.sa" "pub/mirrors/ftp.xemacs.org/packages")
  ("aarnet.edu.au (Australia)" "mirror.aarnet.edu.au" "pub/xemacs/packages"))
)
 '(font-lock-maximum-size '((t))
)
 '(recent-files-permanent-first t)
 '(recent-files-add-menu-before "Hex Edit File...")
 '(w3-default-homepage "http://cscape.wcomnet.com/")
 '(gnus-play-startup-jingle t)
 '(cvs-allow-dir-commit t)
 '(toolbar-info-use-separate-frame nil)
 '(line-number-mode t)
 '(dired-verify-modtimes nil)
 '(cvs-display-full-path nil)
 '(mail-user-agent 'message-user-agent)
 '(ldap-host-parameters-alist '(("teamnet-dev" base "o=WorldCom, c=US" scope subtree))
)
 '(message-default-mail-headers "BCC: paul.houghton@wcom.com\nReply-to: paul.houghton@wcom.com\n")
 '(toolbar-mail-reader 'vm)
 '(dired-gnutar-program "/Tools/bin/tar")
 '(toolbar-news-use-separate-frame nil)
 '(ediff-window-setup-function 'ediff-setup-windows-plain)
 '(recent-files-non-permanent-submenu nil)
 '(recent-files-include-save-now t)
 '(recent-files-menu-path '("File")
)
 '(font-lock-verbose nil)
 '(save-some-buffers-query-display-buffer nil)
 '(font-lock-auto-fontify t)
 '(toolbar-visible-p nil)
 '(cvs-edit-confirm 'changed))
(custom-set-faces
 '(default ((t (:background "white"))) t))
