(custom-set-variables
 '(toolbar-visible-p nil)
 '(interprogram-cut-function nil)
 '(interprogram-paste-function nil)
 '(mwheel-follow-mouse t)
 '(cvs-edit-confirm 'changed)
 '(recent-files-commands-submenu t)
 '(recent-files-permanent-first t)
 '(recent-files-non-permanent-submenu nil)
 '(recent-files-include-save-now t)
 '(recent-files-menu-path '("File")
)
 '(recent-files-add-menu-before "Open...")
 '(sgml-catalog-files '("CATALOG" "/export/home/houghton/work/Support/share/dtd/DocTools/CATALOG" "/Tools/lib/xemacs/xemacs-packages/etc/psgml/CATALOG")
)
 '(c-default-style '((java-mode . "java")
  (other . "gnu"))
)
 '(line-number-mode t)
 '(dired-verify-modtimes nil)
 '(dired-gnutar-program "/Tools/bin/tar")
 '(ldap-host-parameters-alist '(("teamnet-dev" base "o=WorldCom, c=US" scope subtree))
)
 '(ediff-window-setup-function 'ediff-setup-windows-plain)
 '(save-some-buffers-query-display-buffer nil)
 '(mode-compile-make-options "")
 )
(custom-set-faces
 '(default ((t (:background "white"))) t)
 '(buffers-tab ((t (:background "white"))) t))

