(load-file "../../tests_tmp/emacs-test-simple/test-simple.el")
(setq load-path (append '("../../src/pah-misc") load-path))
(test-simple-start "test for timestamp.el")
(assert-t (load-file "../../src/pah-misc/timestamp.el")
	  "require timestamp failed")
(assert-t (timestamp)
	  "timestamp function returned nil")
(end-tests)
